<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Deal extends Model
{
    protected $fillable = [
        'category_id', 'merchant_id', 'title', 'original_price', 
        'discounted_price', 'coupon_code', 'promo_code', 'url', 'short_url', 'image_path', 'status', 'brand',
        'features', 'verdict', 'trust_metrics', 'ai_caption', 'ai_score', 'slug', 'hash_id'
    ];

    protected static function booted()
    {
        static::creating(function ($deal) {
            if (empty($deal->slug)) {
                $baseSlug = Str::slug($deal->title);
                $slug = $baseSlug;
                $count = 1;
                while (static::where('slug', $slug)->exists()) {
                    $slug = $baseSlug . '-' . $count++;
                }
                $deal->slug = $slug;
            }
            if (empty($deal->hash_id)) {
                $hash = Str::random(6);
                while (static::where('hash_id', $hash)->exists()) {
                    $hash = Str::random(6);
                }
                $deal->hash_id = $hash;
            }
        });
    }

    protected $casts = [
        'features' => 'array',
    ];

    public function merchant()
    {
        return $this->belongsTo(Merchant::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function priceHistories()
    {
        return $this->hasMany(PriceHistory::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * Generate a fallback slug for deals missing one in DB.
     * IMPORTANT: must only 'return', never assign $this->slug or saveQuietly()
     * to avoid infinite recursion.
     */
    public function getSlugAttribute($value)
    {
        if (!empty($value)) {
            return $value;
        }
        $baseSlug = \Illuminate\Support\Str::slug($this->attributes['title'] ?? '');
        return ($baseSlug ?: 'deal') . '-' . ($this->attributes['id'] ?? 0);
    }

    /**
     * Generate a fallback hash_id for deals missing one in DB.
     * Returns the numeric ID as string so links don't break.
     */
    public function getHashIdAttribute($value)
    {
        if (!empty($value)) {
            return $value;
        }
        return (string) ($this->attributes['id'] ?? 0);
    }

    public function resolveRouteBinding($value, $field = null)
    {
        if ($field === 'slug') {
            // Try exact slug match first
            $deal = $this->where('slug', $value)->first();
            if ($deal) {
                return $deal;
            }
            // Fallback: extract trailing ID from slug (e.g. "puma-sneakers-413" -> id 413)
            if (preg_match('/-(\d+)$/', $value, $matches)) {
                return $this->find($matches[1]);
            }
            return null;
        }
        
        if ($field === 'hash_id') {
            $deal = $this->where('hash_id', $value)->first();
            if ($deal) {
                return $deal;
            }
            // Numeric fallback: treat as ID
            if (is_numeric($value)) {
                return $this->find($value);
            }
            return null;
        }

        return parent::resolveRouteBinding($value, $field);
    }

    /**
     * Helper to get the fully constructed affiliate URL.
     */
    public function getAffiliateUrlAttribute()
    {
        if ($this->short_url) {
            return $this->short_url;
        }

        $url = $this->url;
        
        // Check if it's an Amazon URL
        if (\Illuminate\Support\Str::contains($url, ['amazon.in', 'amazon.com'])) {
            $urlParts = parse_url($url);
            
            // Extract ASIN to shorten the URL path
            $asin = null;
            $path = $urlParts['path'] ?? '';
            if (preg_match('/\/dp\/([A-Z0-9]{10})/i', $path, $matches)) {
                $asin = $matches[1];
            } elseif (preg_match('/\/gp\/product\/([A-Z0-9]{10})/i', $path, $matches)) {
                $asin = $matches[1];
            }
            
            $queryParams = [];
            
            if (isset($urlParts['query'])) {
                parse_str($urlParts['query'], $queryParams);
            }
            
            // Ensure standard Amazon Affiliate Tracking Params
            $queryParams['linkCode'] = 'll2';
            $queryParams['tag'] = 'kridaymart-21'; // Store ID
            
            // LinkId is normally generated by SiteStripe. If not present, we can just leave it out or provide a dummy one.
            if (!isset($queryParams['linkId'])) {
                $queryParams['linkId'] = '9c069790f13a8b75cb7b4a3989e1698d'; // Keep consistent format
            }
            
            $queryParams['ref_'] = 'as_li_ss_tl';
            
            // Optional: clean up junk tracking parameters to keep it short
            unset($queryParams['pd_rd_w'], $queryParams['pd_rd_wg'], $queryParams['pd_rd_r'], $queryParams['pf_rd_p'], $queryParams['pf_rd_r']);
            
            $urlParts['query'] = http_build_query($queryParams);
            
            // Shorten the path if ASIN found
            if ($asin) {
                $path = '/dp/' . $asin;
            }
            
            return $urlParts['scheme'] . '://' . $urlParts['host'] . $path . '?' . $urlParts['query'];
        }

        $merchant = $this->merchant;
        if (!$merchant) {
            return $url;
        }

        $separator = \Illuminate\Support\Str::contains($url, '?') ? '&' : '?';
        return $url . $separator . $merchant->affiliate_param_key . '=' . $merchant->store_id;
    }
}
