name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
        coverage: none

    - name: Install Composer Dependencies
      run: |
        cd backend
        cp .env.example .env
        composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist
        php artisan key:generate

    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_PRODUCTION_USERNAME }}
        password: ${{ secrets.FTP_PRODUCTION_PASSWORD }}
        local-dir: ./backend/
        server-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          tests/**
          .env
